site_name: testing
theme:
  name: readthedocs
  prev_next_buttons_location: both
use_directory_urls: false
plugins:
  - search
  - alternate-link
nav:
      - Documentation Home: Home.md
      - Index : index.md
